Repository openenclave/test-infra, pull requests merged in 2020-12, with the labels that each got.

#276 add dns caching service to prow
  config/prow/README.md
  config/prow/cluster/nodelocaldns.yaml
Labels: approved, lgtm

#289 add common oe8 build function
  config/jobs/oeedger8r-cpp/jenkins/Rhel8Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/Ubuntu1604Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/Ubuntu1804Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/Windows2016Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/Windows2019Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/common.groovy
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#290 clean up oe8 builds
  config/jobs/oeedger8r-cpp/jenkins/Rhel8Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/Ubuntu1604Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/Ubuntu1804Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/Windows2016Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/Windows2019Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/common.groovy
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#291 combine jenkins files
  config/jobs/oeedger8r-cpp/jenkins/RhelBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/Ubuntu1604Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/Windows2016Build.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/WindowsBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/common.groovy
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#294 switch oe8 to declarative
  config/jobs/oeedger8r-cpp/jenkins/common.groovy
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/M

#297 split ubuntu build into multi stage
  config/jobs/oeedger8r-cpp/jenkins/RhelBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/WindowsBuild.Jenkinsfile
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/M

#298 spacing clean up
  config/jobs/oeedger8r-cpp/jenkins/common.groovy
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/M

#299 add first gcc linux tasK
  config/jobs/oeedger8r-cpp/jenkins/RhelBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/common.groovy
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/XS

#301 add stewarts python changes
  hack/jenkins_bootstrap.py
Labels: approved, area/scripts, dco-signoff: yes, lgtm, sig/ci, size/L

#302 encode all the prints
  hack/jenkins_bootstrap.py
Labels: approved, lgtm

#300 add gcc implementation
  config/jobs/oeedger8r-cpp/jenkins/common.groovy
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/XS

#304 add msvc compiler variable
  config/jobs/oeedger8r-cpp/jenkins/WindowsBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/common.groovy
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/M

#305 remove done todos
  config/jobs/oeedger8r-cpp/jenkins/common.groovy
  config/jobs/openenclave/openenclave-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/S

#306 Refactor pull number, revert if fails
  config/jobs/oeedger8r-cpp/jenkins/RhelBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/WindowsBuild.Jenkinsfile
Labels: approved, dco-signoff: yes, sig/ci, size/XS

#309 refactor oeedg8r
  config/jobs/openenclave/jenkins/Rhel8Build.Jenkinsfile
  config/jobs/openenclave/jenkins/RhelBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/Ubuntu1604Build.Jenkinsfile
  config/jobs/openenclave/jenkins/Ubuntu1804Build.Jenkinsfile
  config/jobs/openenclave/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/Windows2016Build.Jenkinsfile
  config/jobs/openenclave/jenkins/Windows2019Build.Jenkinsfile
  config/jobs/openenclave/jenkins/WindowsBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/common.groovy
  config/jobs/openenclave/jenkins/common2.groovy
  config/jobs/openenclave/openenclave-intel-periodics.yaml
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/openenclave/templates/OWNERS
  config/jobs/openenclave/templates/README.md
  config/jobs/openenclave/templates/config.yml
  config/jobs/openenclave/templates/general/acc/periodics.yml
  config/jobs/openenclave/templates/general/acc/postsubmits.yml
  config/jobs/openenclave/templates/general/acc/pre-submits.yml
  config/jobs/openenclave/templates/general/jenkins/complex/host-verify/periodics.yml
  config/jobs/openenclave/templates/general/jenkins/complex/host-verify/postsubmits.yml
  config/jobs/openenclave/templates/general/jenkins/complex/host-verify/pre-submits.yml
  config/jobs/openenclave/templates/general/jenkins/complex/linuxelf/periodics.yml
  config/jobs/openenclave/templates/general/jenkins/complex/linuxelf/postsubmits.yml
  config/jobs/openenclave/templates/general/jenkins/complex/linuxelf/pre-submits.yml
  config/jobs/openenclave/templates/general/jenkins/rhel/periodics.yml
  config/jobs/openenclave/templates/general/jenkins/rhel/postsubmits.yml
  config/jobs/openenclave/templates/general/jenkins/rhel/pre-submits.yml
  config/jobs/openenclave/templates/general/jenkins/windows/periodics.yml
  config/jobs/openenclave/templates/general/jenkins/windows/postsubmits.yml
  config/jobs/openenclave/templates/general/jenkins/windows/pre-submits.yml
  config/jobs/openenclave/templates/general/periodics.yml
  config/jobs/openenclave/templates/general/postsubmits.yml
  config/jobs/openenclave/templates/general/pre-submits.yml
  config/jobs/openenclave/templates/generate.sh
  config/jobs/openenclave/templates/headers/periodics.yml
  config/jobs/openenclave/templates/headers/postsubmits.yml
  config/jobs/openenclave/templates/headers/pre-submits.yml
  config/jobs/openenclave/templates/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/templates/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/templates/openenclave/openenclave-pre-submits.yaml
  config/jobs/templates/OWNERS
  config/jobs/templates/config.yml
  config/jobs/templates/generate.sh
  config/jobs/templates/test-infra/periodics.yml
  config/jobs/templates/test-infra/postsubmits.yml
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
  hack/jenkins_bootstrap.py
Labels: approved, area/scripts, dco-signoff: yes, sig/ci, size/XXL

#311 refactor openenclave-curl jobs
  config/jobs/config.yml
  config/jobs/generate.sh
  config/jobs/openenclave-curl/jenkins/Rhel8Build.Jenkinsfile
  config/jobs/openenclave-curl/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/openenclave-curl/jenkins/WindowsBuild.Jenkinsfile
  config/jobs/openenclave-curl/jenkins/common.groovy
  config/jobs/openenclave-curl/openenclave-curl-periodics.yaml
  config/jobs/openenclave-curl/openenclave-curl-postsubmits.yaml
  config/jobs/openenclave-curl/openenclave-curl-pre-submits.yaml
  config/jobs/templates/config.yml
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/XL

#312 add rest of repos
  config/jobs/gperftools/gperftools-periodics.yaml
  config/jobs/gperftools/gperftools-postsubmits.yaml
  config/jobs/gperftools/gperftools-pre-submits.yaml
  config/jobs/openenclave-build/openenclave-build-periodics.yaml
  config/jobs/openenclave-build/openenclave-build-postsubmits.yaml
  config/jobs/openenclave-build/openenclave-build-pre-submits.yaml
  config/jobs/openenclave-site/openenclave-site-periodics.yaml
  config/jobs/openenclave-site/openenclave-site-postsubmits.yaml
  config/jobs/openenclave-site/openenclave-site-pre-submits.yaml
  config/jobs/openenclave-template/openenclave-template-periodics.yaml
  config/jobs/openenclave-template/openenclave-template-postsubmits.yaml
  config/jobs/openenclave-template/openenclave-template-pre-submits.yaml
  config/jobs/public-talks/public-talks-periodics.yaml
  config/jobs/public-talks/public-talks-postsubmits.yaml
  config/jobs/public-talks/public-talks-pre-submits.yaml
  config/jobs/templates/config.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#313 Lvi
  config/jobs/openenclave/jenkins/RhelBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/WindowsBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/common.groovy
  config/jobs/templates/config.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/S

#314 Package
  config/jobs/openenclave/jenkins/RhelBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/WindowsBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/common.groovy
Labels: approved, dco-signoff: yes, sig/ci, size/L

#315 add ci ping jobs for all
  config/jobs/gperftools/gperftools-periodics.yaml
  config/jobs/gperftools/gperftools-postsubmits.yaml
  config/jobs/gperftools/gperftools-pre-submits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-periodics.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-postsubmits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-pre-submits.yaml
  config/jobs/openenclave-build/openenclave-build-periodics.yaml
  config/jobs/openenclave-build/openenclave-build-postsubmits.yaml
  config/jobs/openenclave-build/openenclave-build-pre-submits.yaml
  config/jobs/openenclave-ci/openenclave-ci-periodics.yaml
  config/jobs/openenclave-ci/openenclave-ci-postsubmits.yaml
  config/jobs/openenclave-ci/openenclave-ci-pre-submits.yaml
  config/jobs/openenclave-curl/openenclave-curl-periodics.yaml
  config/jobs/openenclave-curl/openenclave-curl-postsubmits.yaml
  config/jobs/openenclave-curl/openenclave-curl-pre-submits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-periodics.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-postsubmits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-pre-submits.yaml
  config/jobs/openenclave-site/openenclave-site-periodics.yaml
  config/jobs/openenclave-site/openenclave-site-postsubmits.yaml
  config/jobs/openenclave-site/openenclave-site-pre-submits.yaml
  config/jobs/openenclave-template/openenclave-template-periodics.yaml
  config/jobs/openenclave-template/openenclave-template-postsubmits.yaml
  config/jobs/openenclave-template/openenclave-template-pre-submits.yaml
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/public-talks/public-talks-periodics.yaml
  config/jobs/public-talks/public-talks-postsubmits.yaml
  config/jobs/public-talks/public-talks-pre-submits.yaml
  config/jobs/templates/config.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/XL

#316 change oe jenkins file to only build 1 mode
  config/jobs/openenclave/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/templates/config.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/XL

#319 Refactor ubuntu
  config/jobs/openenclave/jenkins/RhelBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/templates/config.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#318 Rhel split2
  config/jobs/openenclave/jenkins/RhelBuild.Jenkinsfile
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/templates/config.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#321 clean up ubuntu oe
  config/jobs/openenclave/jenkins/RhelBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/templates/config.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#323 split out snmalloc jobs
  config/jobs/openenclave/jenkins/common.groovy
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/templates/config.yml
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/XXL, ¯\_(ツ)_/¯

#325 extend intel buil time to 1 hour
  config/jobs/openenclave/openenclave-intel-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/XS

#191 Jenkins as code on AKS
  config/jenkins/README.md
  config/jenkins/configuration/clouds.yml
  config/jenkins/configuration/jenkins.yml
  config/jenkins/configuration/jobs/master/reload-configuration.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/Ubuntu1804Build.yml
  config/jenkins/configuration/jobs/openenclave/hostverify.yml
  config/jenkins/configuration/jobs/openenclave/linuxelfbuild.yml
  config/jenkins/configuration/jobs/openenclave/rhel8build.yml
  config/jenkins/configuration/jobs/openenclave/ubuntu1604build.yml
  config/jenkins/configuration/jobs/openenclave/ubuntu1804build.yml
  config/jenkins/configuration/jobs/openenclave/windows2016build.yml
  config/jenkins/configuration/jobs/openenclave/windows2019build.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Ubuntu1804Build.yml
  config/jenkins/deploy_jenkins.sh
  config/jenkins/kubernetes/jenkins-ingress.yml
  config/jenkins/kubernetes/jenkins-master-deployment.yml
  config/jenkins/master/install-plugins.sh
  config/jenkins/master/plugins.txt
  config/jenkins/master/setup.sh
  config/jenkins/plugins.txt
  config/jobs/openenclave/jenkins/ubuntu1804.Jenkinsfile
Labels: approved, area/jenkins, dco-signoff: yes, ok-to-test, sig/ci, size/XXL

#329 Host verify
  config/jobs/openenclave/jenkins/common.groovy
  config/jobs/openenclave/jenkins/common2.groovy
  config/jobs/openenclave/jenkins/hostverify.Jenkinsfile
  config/jobs/openenclave/jenkins/linuxelfbuild.Jenkinsfile
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-periodics.yml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-postsubmits.yml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yml
  config/jobs/templates/config.yml
  config/jobs/templates/jenkins/periodics.yml
  config/jobs/templates/test-infra/periodics.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-periodics.yml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-postsubmits.yml
  config/jobs/test-infra/test-infra-pre-submits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/XXL

#324 add DSL's for initial review
  config/jenkins/configuration/jobs/oeedger8r-cpp/Rhel8BuildClang-8.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/Rhel8BuildGCC.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/Ubuntu1604BuildClang-7.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/Ubuntu1604BuildGCC.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/Ubuntu1804BuildClang-7.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/Ubuntu1804BuildGCC.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/Windows2016Build.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/Windows2019Build.yml
  config/jenkins/configuration/jobs/openenclave-curl/Ubuntu1604BuildClang-7.yml
  config/jenkins/configuration/jobs/openenclave-curl/Ubuntu1804BuildClang-7.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/Rhel8BuildClang-8.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/Rhel8BuildGCC.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/Ubuntu1604BuildClang-7.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/Ubuntu1604BuildGCC.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/Ubuntu1804BuildClang-7.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/Ubuntu1804BuildGCC.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/Windows2016Build.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/Windows2019Build.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Rhel8BuildClang-8.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Rhel8BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Ubuntu1604BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Ubuntu1604BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Ubuntu1804BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Ubuntu1804BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Windows2016Build.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Windows2019Build.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-curl/Ubuntu1604BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-curl/Ubuntu1804BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Rhel8BuildClang-8.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Rhel8BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Ubuntu1604BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Ubuntu1604BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Ubuntu1804BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Ubuntu1804BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Windows2016Build.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Windows2019Build.yml
Labels: approved, area/prow, dco-signoff: yes, lgtm, sig/ci, size/XXL

#330 Add ping jobs for Prow
  config/jenkins/configuration/jobs/oeedger8r-cpp/ping.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/ping.yml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, sig/ci, size/M

#331 remove ping paramters
  config/jenkins/configuration/jobs/oeedger8r-cpp/ping.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/ping.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/S

#333 change misnamed Jenkins display name
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Rhel8BuildClang-8.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Rhel8BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Ubuntu1604BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Ubuntu1604BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Ubuntu1804BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Ubuntu1804BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Windows2016Build.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Windows2019Build.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-curl/Ubuntu1604BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-curl/Ubuntu1804BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Rhel8BuildClang-8.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Rhel8BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Ubuntu1604BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Ubuntu1604BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Ubuntu1804BuildClang-7.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Ubuntu1804BuildGCC.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Windows2016Build.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Windows2019Build.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/M

#334 multi regions
  config/jenkins/configuration/clouds.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#336 add aks jenkins as replica
  config/prow/secondary/config.yaml
Labels: approved, area/prow, dco-signoff: yes, lgtm, sig/ci, size/XS

#335 change regions to include east us and west us
  config/jenkins/configuration/clouds.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/M

#337 add primary cluster config to poing towards aks jenkins
  config/prow/primary/config.yaml
Labels: approved, area/prow, dco-signoff: yes, lgtm, sig/ci, size/XS

#338 add gpfertools ping jobs
  config/jenkins/configuration/jobs/gperftools/ping.yml
  config/jenkins/configuration/jobs/test-infra/gperftools/ping.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/M

#340 Update Cloud config locations
  config/jenkins/configuration/clouds.yml
  config/jenkins/deploy_jenkins.sh
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, sig/ci, size/M

#339 Automated configuration updates
  config/jenkins/README.md
  config/jenkins/configuration-reload.sh
  config/jenkins/configuration/jenkins.yml
  config/jenkins/deploy_jenkins.sh
  config/jenkins/kubernetes/configuration-update.yml
  config/jenkins/kubernetes/jenkins-master-deployment.yml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, sig/ci, size/XL

#341 Fix typos
  config/jenkins/configuration/clouds.yml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, sig/ci, size/XS

#342 add windows e2e jobs
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/templates/config.yml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#346 add parameters to ping for compatability
  config/jenkins/configuration/jobs/gperftools/ping.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/ping.yml
  config/jenkins/configuration/jobs/openenclave-build/ping.yml
  config/jenkins/configuration/jobs/openenclave-ci/ping.yml
  config/jenkins/configuration/jobs/openenclave-curl/ping.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/ping.yml
  config/jenkins/configuration/jobs/openenclave-site/ping.yml
  config/jenkins/configuration/jobs/openenclave-template/ping.yml
  config/jenkins/configuration/jobs/openenclave/ping.yml
  config/jenkins/configuration/jobs/public-talks/ping.yml
  config/jenkins/configuration/jobs/test-infra/gperftools/ping.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-build/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-ci/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-curl/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-site/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-template/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/ping.yml
  config/jenkins/configuration/jobs/test-infra/public-talks/ping.yml
  config/jobs/templates/jenkins/jobs/ping.yml
  config/jobs/templates/jenkins/jobs/test-infra/ping.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#347 fix windows version bug
  config/jenkins/configuration/jobs/oeedger8r-cpp/Windows2016Build.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/Windows2019Build.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/Windows2016Build.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/Windows2019Build.yml
  config/jenkins/configuration/jobs/openenclave/HostVerifyDeb16042019.yml
  config/jenkins/configuration/jobs/openenclave/HostVerifyDeb18042019.yml
  config/jenkins/configuration/jobs/openenclave/HostVerifyRel16042019.yml
  config/jenkins/configuration/jobs/openenclave/HostVerifyRel18042019.yml
  config/jenkins/configuration/jobs/openenclave/LinuxElfDeb16042019.yml
  config/jenkins/configuration/jobs/openenclave/LinuxElfDeb18042019.yml
  config/jenkins/configuration/jobs/openenclave/LinuxElfRel16042019.yml
  config/jenkins/configuration/jobs/openenclave/LinuxElfRel18042019.yml
  config/jenkins/configuration/jobs/openenclave/Win2016Debug.yml
  config/jenkins/configuration/jobs/openenclave/Win2016DebugSnmalloc.yml
  config/jenkins/configuration/jobs/openenclave/Win2016DebugSnmallocE2E.yml
  config/jenkins/configuration/jobs/openenclave/Win2016RelSnmalloc.yml
  config/jenkins/configuration/jobs/openenclave/Win2016RelSnmallocE2E.yml
  config/jenkins/configuration/jobs/openenclave/Win2016Release.yml
  config/jenkins/configuration/jobs/openenclave/Win2019Debug.yml
  config/jenkins/configuration/jobs/openenclave/Win2019DebugSnmalloc.yml
  config/jenkins/configuration/jobs/openenclave/Win2019DebugSnmallocE2E.yml
  config/jenkins/configuration/jobs/openenclave/Win2019RelSnmalloc.yml
  config/jenkins/configuration/jobs/openenclave/Win2019RelSnmallocE2E.yml
  config/jenkins/configuration/jobs/openenclave/Win2019Release.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Windows2016Build.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/Windows2019Build.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Windows2016Build.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/Windows2019Build.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/HostVerifyDeb16042019.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/HostVerifyDeb18042019.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/HostVerifyRel16042019.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/HostVerifyRel18042019.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/LinuxElfDeb16042019.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/LinuxElfDeb18042019.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/LinuxElfRel16042019.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/LinuxElfRel18042019.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2016Debug.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2016DebugSnmalloc.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2016DebugSnmallocE2E.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2016RelSnmalloc.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2016RelSnmallocE2E.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2016Release.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2019Debug.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2019DebugSnmalloc.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2019DebugSnmallocE2E.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2019RelSnmalloc.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2019RelSnmallocE2E.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Win2019Release.yml
  config/jobs/templates/config.yml
Labels: approved, dco-signoff: yes, sig/ci, size/M

#350 Remove lock files due to terminated config updates
  config/jenkins/configuration-reload.sh
  config/jenkins/kubernetes/configuration-update.yml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, sig/ci, size/S

#349 remove past job dsls
  config/jenkins/configuration/jobs/openenclave/hostverify.yml
  config/jenkins/configuration/jobs/openenclave/linuxelfbuild.yml
  config/jenkins/configuration/jobs/openenclave/rhel8build.yml
  config/jenkins/configuration/jobs/openenclave/ubuntu1604build.yml
  config/jenkins/configuration/jobs/openenclave/ubuntu1804build.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/L

#351 move ping jobs to overwatch
  config/jenkins/configuration/jobs/gperftools/ping.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/ping.yml
  config/jenkins/configuration/jobs/openenclave-build/ping.yml
  config/jenkins/configuration/jobs/openenclave-ci/ping.yml
  config/jenkins/configuration/jobs/openenclave-curl/ping.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/ping.yml
  config/jenkins/configuration/jobs/openenclave-site/ping.yml
  config/jenkins/configuration/jobs/openenclave-template/ping.yml
  config/jenkins/configuration/jobs/openenclave/ping.yml
  config/jenkins/configuration/jobs/public-talks/ping.yml
  config/jenkins/configuration/jobs/test-infra/gperftools/ping.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-build/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-ci/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-curl/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-site/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-template/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/ping.yml
  config/jenkins/configuration/jobs/test-infra/public-talks/ping.yml
  config/jobs/templates/jenkins/jobs/ping.yml
  config/jobs/templates/jenkins/jobs/test-infra/ping.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/S
