Repository openenclave/test-infra, pull requests merged in 2020-07, with the labels that each got.

#5 Onboard test-infra
  .gitignore
  CONTRIBUTING.md
  OWNERS
  config/OWNERS
  config/jobs/OWNERS
  config/jobs/oeedger8r-cpp/OWNERS
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-periodics.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-presubmits.yaml
  config/jobs/openenclave-sdk/OWNERS
  config/jobs/openenclave-sdk/openenclave-periodics.yaml
  config/jobs/test-infra/OWNERS
  config/jobs/test-infra/test-infra-presubmits.yaml
  config/prow/OWNERS
  config/prow/README.md
  config/prow/cluster/OWNERS
  config/prow/config.yaml
  config/prow/plugins.yaml
  hack/OWNERS
  images/OWNERS
  images/debian/1604/OWNERS
  images/debian/1804/OWNERS
  images/debian/OWNERS
  images/windows/2019/OWNERS
  images/windows/OWNERS
Labels: dco-signoff: no, do-not-merge/invalid-owners-file, ok-to-test, size/L

#6 add Test-infra ReadMe.md
  CONTRIBUTING.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#7 add checkout scm script
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-periodics.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-presubmits.yaml
  config/jobs/openenclave-sdk/openenclave-periodics.yaml
  config/jobs/test-infra/test-infra-presubmits.yaml
  config/prow/Dockerfile
  config/prow/README.md
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_rbac.yaml
  config/prow/cluster/starter.yaml
  config/prow/config.yaml
  config/prow/plugins.yaml
  hack/checkout-scm.sh
  hack/cmake-build.sh
  hack/validate-prow-configs.sh
  hack/validate-prow-jobs.sh
Labels: dco-signoff: no, do-not-merge/hold, ok-to-test, size/XL

#10 change test infra periodic to use test infra image
  .github/bug_report.md
  .github/cleanup.md
  .github/enhancement.md
  README.md
  config/jobs/openenclave-sdk/openenclave-periodics.yaml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-presubmits.yaml
  config/prow/README.md
  hack/merge-prow-jobs.sh
  hack/validate-prow-jobs.sh
  images/images-e2e.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#13 Update image configs
  config/jobs/openenclave-sdk/openenclave-periodics.yaml
  hack/checkout-scm.sh
  hack/cmake-build.sh
  images/debian/setup.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#14 Jenkins integration
  README.md
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-periodics.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-presubmits.yaml
  config/jobs/openenclave-sdk/openenclave-periodics.yaml
  config/jobs/openenclave-sdk/openenclave-presubmits.yaml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/prow/README.md
  config/prow/cluster/configs.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_rbac.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/deck_rbac.yaml
  config/prow/cluster/deck_service.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_rbac.yaml
  config/prow/cluster/hook_service.yaml
  config/prow/cluster/horolgium_deployment.yaml
  config/prow/cluster/horolgium_rbac.yaml
  config/prow/cluster/ing_ingress.yaml
  config/prow/cluster/jenkins_deployment.yaml
  config/prow/cluster/jenkins_rbac.yaml
  config/prow/cluster/jenkins_service.yaml
  config/prow/cluster/plank_deployment.yaml
  config/prow/cluster/plank_rbac.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/sinker_rbac.yaml
  config/prow/cluster/starter.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/statusreconciler_rbac.yaml
  config/prow/cluster/test_pods.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/cluster/tide_rbac.yaml
  config/prow/cluster/tide_service.yaml
  config/prow/config.yaml
  hack/prowsetupe2e.sh
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#16 upgrade cmake with optional parameters
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/cleanup.md
  .github/ISSUE_TEMPLATE/enhancement.md
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-presubmits.yaml
  config/prow/config.yaml
  hack/cmake-build.sh
  hack/merge-prow-jobs.sh
  hack/prowsetupe2e.sh
  hack/validate-prow-jobs.sh
  images/bootstap/Dockerfile
  images/images-e2e.yml
Labels: approved, dco-signoff: no, size/L

#18 add test infra post submit builds
  config/jobs/openenclave-sdk/openenclave-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#19 refactor naming job scheme to match badges
  README.md
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-presubmits.yaml
  config/jobs/openenclave-sdk/openenclave-presubmits.yaml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#20 Add plugin and validation clean up
  config/prow/plugins.yaml
  hack/cmake-build.sh
  images/debian/validate.sh
  images/images-e2e.yml
Labels: approved, dco-signoff: yes, lgtm, size/S, ¯\_(ツ)_/¯

#21 Abstract out docker image testing
  config/jobs/test-infra/test-infra-presubmits.yaml
  hack/checkout-scm.sh
  hack/cmake-build.sh
  images/debian/validate.sh
  images/test/build.sh
  images/test/validate.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#22 refactor script set up and base rhel 8 image
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-presubmits.yaml
  images/debian/1604/Dockerfile
  images/debian/1804/Dockerfile
  images/rhel/8.1/Dockerfile
  images/rhel/8.1/OWNERS
  images/rhel/OWNERS
  images/scripts/setup.sh
  images/test/build.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#25 add post build badge
  README.md
  images/images-e2e.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#27 Create stale.yml
  .github/workflows/stale.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#31 Add Git Guardian badge
  .github/workflows/secretscanner.yml
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#30 add secret scanning action
  .github/workflows/secretscanner.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#32 low max prow pod age
  config/prow/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#29 Create label.yml
  .github/labeler.yml
  .github/workflows/label.yml
Labels: approved, dco-signoff: yes, lgtm, size/M, workflows

#33 Conf update
  README.md
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
  config/jobs/test-infra/test-infra-presubmits.yaml
  config/prow/config.yaml
  hack/prowsetupe2e.sh
  images/scripts/setup.sh
  images/test/build.sh
Labels: approved, dco-signoff: yes, docs, lgtm, size/M, test-infra/test-infra

#34 Add TODO Bot
  .github/workflows/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#36 Update Owners and Read Me files
  OWNERS
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS, ¯\_(ツ)_/¯
