Repository openenclave/test-infra, pull requests merged in 2021-01, with the labels that each got.

#352 reduce jenkins quiet period to 0
  config/jenkins/configuration/jenkins.yml
Labels: approved, area/scripts, dco-signoff: yes, lgtm, sig/ci, size/XS

#354 change scm retry count to 10
  config/jenkins/configuration/jenkins.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, size/XS

#355 Reorder operations to prevent broken sp secret
  config/jenkins/deploy_jenkins.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, sig/ci, size/S

#357 Minor updates to configuration and deployment
  config/jenkins/configuration-reload.sh
  config/jenkins/deploy_jenkins.sh
  config/jenkins/kubernetes/configuration-update.yml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, sig/ci, size/XS

#359 Dolla dolla
  config/jenkins/configuration/jobs/test-infra/gperftools/ping.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-build/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-ci/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-curl/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-site/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-template/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/ping.yml
  config/jenkins/configuration/jobs/test-infra/public-talks/ping.yml
  config/jobs/templates/jenkins/jobs/HostVerify.yml
  config/jobs/templates/jenkins/jobs/LinuxElfBuild.yml
  config/jobs/templates/jenkins/jobs/RhelBuild.yml
  config/jobs/templates/jenkins/jobs/UbuntuBuild.yml
  config/jobs/templates/jenkins/jobs/WindowsBuild.yml
  config/jobs/templates/jenkins/jobs/ping.yml
  config/jobs/templates/jenkins/jobs/test-infra/HostVerify.yml
  config/jobs/templates/jenkins/jobs/test-infra/LinuxElfBuild.yml
  config/jobs/templates/jenkins/jobs/test-infra/RhelBuild.yml
  config/jobs/templates/jenkins/jobs/test-infra/UbuntuBuild.yml
  config/jobs/templates/jenkins/jobs/test-infra/WindowsBuild.yml
  config/jobs/templates/jenkins/jobs/test-infra/ping.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#362 add new jenkins prod config
  config/prow/primary/config.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#363 raise the max vms per pergion by 10x
  config/jenkins/configuration/clouds.yml
Labels: approved, dco-signoff: yes, lgtm, sig/testing, size/XS

#364 Cloud bugs
  config/jenkins/configuration/clouds.yml
  config/jenkins/configuration/jobs/openenclave/windows2016build.yml
  config/jenkins/configuration/jobs/openenclave/windows2019build.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#365 Rhel bugs
  config/jenkins/configuration/jobs/openenclave/Rhel8DebugClang-8.yml
  config/jenkins/configuration/jobs/openenclave/Rhel8DebugClang-8Snmalloc.yml
  config/jenkins/configuration/jobs/openenclave/Rhel8DebugClang-8SnmallocE2E.yml
  config/jenkins/configuration/jobs/openenclave/Rhel8ReleaseClang-8.yml
  config/jenkins/configuration/jobs/openenclave/Rhel8ReleaseClang-8Snmalloc.yml
  config/jenkins/configuration/jobs/openenclave/Rhel8ReleaseClang-8SnmallocE2E.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Rhel8DebugClang-8.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Rhel8DebugClang-8Snmalloc.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Rhel8DebugClang-8SnmallocE2E.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Rhel8ReleaseClang-8.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Rhel8ReleaseClang-8Snmalloc.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/Rhel8ReleaseClang-8SnmallocE2E.yml
  config/jobs/templates/config.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#366 Improved production stability of master and agents
  config/jenkins/README.md
  config/jenkins/configuration-reload.sh
  config/jenkins/configuration/clouds.yml
  config/jenkins/deploy_jenkins.sh
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#367 allow concurrent pings
  config/jenkins/configuration/jobs/gperftools/ping.yml
  config/jenkins/configuration/jobs/oeedger8r-cpp/ping.yml
  config/jenkins/configuration/jobs/openenclave-build/ping.yml
  config/jenkins/configuration/jobs/openenclave-ci/ping.yml
  config/jenkins/configuration/jobs/openenclave-curl/ping.yml
  config/jenkins/configuration/jobs/openenclave-mbedtls/ping.yml
  config/jenkins/configuration/jobs/openenclave-site/ping.yml
  config/jenkins/configuration/jobs/openenclave-template/ping.yml
  config/jenkins/configuration/jobs/openenclave/ping.yml
  config/jenkins/configuration/jobs/public-talks/ping.yml
  config/jenkins/configuration/jobs/test-infra/gperftools/ping.yml
  config/jenkins/configuration/jobs/test-infra/oeedger8r-cpp/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-build/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-ci/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-curl/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-mbedtls/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-site/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave-template/ping.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/ping.yml
  config/jenkins/configuration/jobs/test-infra/public-talks/ping.yml
  config/jobs/templates/jenkins/jobs/ping.yml
  config/jobs/templates/jenkins/jobs/test-infra/ping.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/S

#368 Use advanced image to support VM agent vnet/snet
  config/jenkins/configuration/clouds.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#370 Switch to a supported Gen 2 VM series
  config/jenkins/configuration/clouds.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#379 HPA nginx controllers on dedicated nodes
  config/jenkins/deploy_jenkins.sh
  config/jenkins/kubernetes/ingress-nginx-values.yml
  config/jenkins/kubernetes/jenkins-ingress.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#382 Revert "remove wait timer from templates"
  config/jobs/templates/jenkins/periodics.yml
  config/jobs/templates/jenkins/postsubmits.yml
  config/jobs/templates/jenkins/pre-submits.yml
  config/jobs/templates/test-infra/periodics.yml
  config/jobs/templates/test-infra/postsubmits.yml
  config/jobs/templates/test-infra/pre-submits.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/S

#381 include dcap libraries for attestation in wondows vms
  config/jenkins/configuration/clouds.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/S

#386 add docker windows 2019 base image
  config/jenkins/configuration/clouds.yml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#387 add docker workspace to required plugins
  config/jenkins/plugins.txt
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#369 Validate Prod with labels!
  OWNERS_ALIASES
  config/jobs/gperftools/OWNERS
  config/jobs/oeedger8r-cpp/OWNERS
  config/jobs/openenclave-build/OWNERS
  config/jobs/openenclave-ci/OWNERS
  config/jobs/openenclave-curl/OWNERS
  config/jobs/openenclave-mbedtls/OWNERS
  config/jobs/openenclave-site/OWNERS
  config/jobs/openenclave-template/OWNERS
  config/jobs/openenclave/OWNERS
  config/jobs/public-talks/OWNERS
  config/jobs/templates/OWNERS
  config/jobs/test-infra/OWNERS
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#391 Fixoe ubuntu
  config/jobs/openenclave/jenkins/RhelBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/WindowsBuild.Jenkinsfile
  config/jobs/openenclave/jenkins/common.groovy
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#393 Catch edge case of initial unset config variables
  config/jenkins/configuration-reload.sh
  config/jenkins/deploy_jenkins.sh
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/S

#397 start cleaning up prow configs and plugins
  config/prow/README.md
  config/prow/config.yaml
  config/prow/plugins.yaml
  config/prow/primary/plugins.yaml
  config/prow/secondary/config.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#399 add oesdk logo
  config/prow/config.yaml
Labels: approved, lgtm, sig/ci, sig/testing, size/S

#400 Clean up configs
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L, ¯\_(ツ)_/¯

#396 lower max prow job concurrency to 2
  config/jobs/gperftools/gperftools-pre-submits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-pre-submits.yaml
  config/jobs/openenclave-build/openenclave-build-pre-submits.yaml
  config/jobs/openenclave-ci/openenclave-ci-pre-submits.yaml
  config/jobs/openenclave-curl/openenclave-curl-pre-submits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-pre-submits.yaml
  config/jobs/openenclave-site/openenclave-site-pre-submits.yaml
  config/jobs/openenclave-template/openenclave-template-pre-submits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/public-talks/public-talks-pre-submits.yaml
  config/jobs/templates/jenkins/pre-submits.yml
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra-images/test-infra-images-pre-submits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#401 Comment out favicon
  config/prow/config.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#402 add spyglass config
  config/prow/cluster/deck_deployment.yaml
  config/prow/config.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M, ¯\_(ツ)_/¯

#403 reroute pr logs to spyglass
  config/prow/config.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#404 Syntax
  config/prow/config.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#405 add extra syntax highlighting for gateway issues
  config/prow/config.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#406 highlight job url
  config/prow/config.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#407 add prow config comments
  config/prow/config.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#408 add syntax highlighting for 503 Service Temporarily Unavailable
  config/prow/config.yaml
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/S

#409 switch to using global hmac to prepare for org management
  config/prow/config.yaml
Labels: approved, area/config, area/config/prow, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#410 add label sync script
  hack/label_sync.sh
Labels: approved, area/hack, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#395 modify checkout statements to use string literals
  config/jobs/openenclave-curl/jenkins/common.groovy
  config/jobs/openenclave-mbedtls/jenkins/common.groovy
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#412 add oe-contributors-acc-setup.yml to ansble
  scripts/ansible/oe-contributors-acc-setup.yml
Labels: approved, lgtm, sig/ci, sig/testing, size/S

#413 Use pipeline syntax and secure credentials
  config/jobs/test-infra-hosts/jenkins/LinuxHostBuild.Jenkinsfile
Labels: approved, area/config, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#414 Hide secrets in output
  config/jobs/test-infra-hosts/jenkins/LinuxHostBuild.Jenkinsfile
Labels: approved, area/config, dco-signoff: no, lgtm, sig/ci, sig/testing, size/M

#415 add linux host image builder
  config/jenkins/configuration/jobs/test-infra-hosts/RhelHostBuild.yml
  config/jenkins/configuration/jobs/test-infra-hosts/Ubuntu1604HostBuild.yml
  config/jenkins/configuration/jobs/test-infra-hosts/Ubuntu1804HostBuild.yml
  config/jobs/test-infra-hosts/jenkins/LinuxHostBuild.Jenkinsfile
Labels: approved, area/config, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#417 add test infra hosts ubuntu 1804 dsl
  config/jenkins/configuration/jobs/test-infra-hosts/Ubuntu1804HostBuild.yml
Labels: approved, area/config, dco-signoff: yes, sig/ci, sig/testing, size/XS

#416 add explicit approval requirement for azure resources
  config/jenkins/OWNERS
Labels: approved, area/config, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/S

#419 add daily periodic timer to linux host builds
  config/jenkins/configuration/jobs/test-infra-hosts/RhelHostBuild.yml
  config/jenkins/configuration/jobs/test-infra-hosts/SGXUbuntu1604HostBuild.yml
  config/jenkins/configuration/jobs/test-infra-hosts/SGXUbuntu1804HostBuild.yml
  config/jenkins/configuration/jobs/test-infra-hosts/Ubuntu1604HostBuild.yml
  config/jenkins/configuration/jobs/test-infra-hosts/Ubuntu1804HostBuild.yml
Labels: approved, area/config, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#421 refactor to declarative pipeline ubuntu oe8
  config/jobs/oeedger8r-cpp/jenkins/RhelBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/WindowsBuild.Jenkinsfile
Labels: approved, area/config, config/jobs/oeedger8r-cpp, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#426 remove test infra post submits
  config/jobs/templates/test-infra/postsubmits.yml
  config/jobs/test-infra/test-infra-postsubmits.yaml
Labels: approved, area/config, config/jobs/templates, config/jobs/test-infra, dco-signoff: yes, lgtm, sig/ci, size/XL

#425 increase acc host disk size to 128 gb
  config/jenkins/configuration/clouds.yml
Labels: approved, area/config, config/jenkins, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/S

#420 fix jenkins sgx rhel job name
  config/jenkins/configuration/jobs/test-infra-hosts/SGXRhelHostBuild.yml
Labels: approved, area/config, config/jenkins, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XS

#427 modify test infra pr requirements
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, area/config, config/jobs/templates, config/jobs/test-infra, lgtm, sig/ci, sig/testing, size/L

#423 refactor openenclave curl jenkins file to declarative
  config/jobs/openenclave-curl/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/openenclave-curl/jenkins/common.groovy
Labels: approved, area/config, config/jobs/openenclave-curl, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#429 Jenkinsop2
  config/jobs/gperftools/gperftools-periodics.yaml
  config/jobs/gperftools/gperftools-postsubmits.yaml
  config/jobs/gperftools/gperftools-pre-submits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-periodics.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-postsubmits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-pre-submits.yaml
  config/jobs/openenclave-build/openenclave-build-periodics.yaml
  config/jobs/openenclave-build/openenclave-build-postsubmits.yaml
  config/jobs/openenclave-build/openenclave-build-pre-submits.yaml
  config/jobs/openenclave-ci/openenclave-ci-periodics.yaml
  config/jobs/openenclave-ci/openenclave-ci-postsubmits.yaml
  config/jobs/openenclave-ci/openenclave-ci-pre-submits.yaml
  config/jobs/openenclave-curl/openenclave-curl-periodics.yaml
  config/jobs/openenclave-curl/openenclave-curl-postsubmits.yaml
  config/jobs/openenclave-curl/openenclave-curl-pre-submits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-periodics.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-postsubmits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-pre-submits.yaml
  config/jobs/openenclave-site/openenclave-site-periodics.yaml
  config/jobs/openenclave-site/openenclave-site-postsubmits.yaml
  config/jobs/openenclave-site/openenclave-site-pre-submits.yaml
  config/jobs/openenclave-template/openenclave-template-periodics.yaml
  config/jobs/openenclave-template/openenclave-template-postsubmits.yaml
  config/jobs/openenclave-template/openenclave-template-pre-submits.yaml
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/public-talks/public-talks-periodics.yaml
  config/jobs/public-talks/public-talks-postsubmits.yaml
  config/jobs/public-talks/public-talks-pre-submits.yaml
  config/jobs/templates/jenkins/periodics.yml
  config/jobs/templates/jenkins/postsubmits.yml
  config/jobs/templates/jenkins/pre-submits.yml
  config/jobs/templates/test-infra/periodics.yml
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra-images/test-infra-images-periodics.yaml
  config/jobs/test-infra-images/test-infra-images-postsubmits.yaml
  config/jobs/test-infra-images/test-infra-images-pre-submits.yaml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, area/config, config/jobs/gperftools, config/jobs/oeedger8r-cpp, config/jobs/openenclave, config/jobs/openenclave-build, config/jobs/openenclave-ci, config/jobs/openenclave-curl, config/jobs/openenclave-mbedtls, config/jobs/openenclave-site, config/jobs/openenclave-template, config/jobs/templates, config/jobs/test-infra, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XL

#431 migrate to new python script
  config/jobs/gperftools/gperftools-periodics.yaml
  config/jobs/gperftools/gperftools-postsubmits.yaml
  config/jobs/gperftools/gperftools-pre-submits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-periodics.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-postsubmits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-pre-submits.yaml
  config/jobs/openenclave-build/openenclave-build-periodics.yaml
  config/jobs/openenclave-build/openenclave-build-postsubmits.yaml
  config/jobs/openenclave-build/openenclave-build-pre-submits.yaml
  config/jobs/openenclave-ci/openenclave-ci-periodics.yaml
  config/jobs/openenclave-ci/openenclave-ci-postsubmits.yaml
  config/jobs/openenclave-ci/openenclave-ci-pre-submits.yaml
  config/jobs/openenclave-curl/openenclave-curl-periodics.yaml
  config/jobs/openenclave-curl/openenclave-curl-postsubmits.yaml
  config/jobs/openenclave-curl/openenclave-curl-pre-submits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-periodics.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-postsubmits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-pre-submits.yaml
  config/jobs/openenclave-site/openenclave-site-periodics.yaml
  config/jobs/openenclave-site/openenclave-site-postsubmits.yaml
  config/jobs/openenclave-site/openenclave-site-pre-submits.yaml
  config/jobs/openenclave-template/openenclave-template-periodics.yaml
  config/jobs/openenclave-template/openenclave-template-postsubmits.yaml
  config/jobs/openenclave-template/openenclave-template-pre-submits.yaml
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/public-talks/public-talks-periodics.yaml
  config/jobs/public-talks/public-talks-postsubmits.yaml
  config/jobs/public-talks/public-talks-pre-submits.yaml
  config/jobs/templates/jenkins/periodics.yml
  config/jobs/templates/jenkins/postsubmits.yml
  config/jobs/templates/jenkins/pre-submits.yml
  config/jobs/templates/test-infra/periodics.yml
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra-images/test-infra-images-periodics.yaml
  config/jobs/test-infra-images/test-infra-images-postsubmits.yaml
  config/jobs/test-infra-images/test-infra-images-pre-submits.yaml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, config/jobs/gperftools, config/jobs/oeedger8r-cpp, config/jobs/openenclave, config/jobs/openenclave-build, config/jobs/openenclave-ci, config/jobs/openenclave-curl, config/jobs/openenclave-mbedtls, config/jobs/openenclave-site, config/jobs/openenclave-template, config/jobs/templates, config/jobs/test-infra, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XL

#433 remove all post submit jobs to reduce load
  config/jobs/gperftools/gperftools-postsubmits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-postsubmits.yaml
  config/jobs/openenclave-build/openenclave-build-postsubmits.yaml
  config/jobs/openenclave-ci/openenclave-ci-postsubmits.yaml
  config/jobs/openenclave-curl/openenclave-curl-postsubmits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-postsubmits.yaml
  config/jobs/openenclave-site/openenclave-site-postsubmits.yaml
  config/jobs/openenclave-template/openenclave-template-postsubmits.yaml
  config/jobs/openenclave/openenclave-postsubmits.yaml
  config/jobs/public-talks/public-talks-postsubmits.yaml
  config/jobs/templates/config.yml
  config/jobs/templates/test-infra/postsubmits.yml
  config/jobs/test-infra-images/test-infra-images-postsubmits.yaml
  config/jobs/test-infra/test-infra-postsubmits.yaml
Labels: approved, area/config, config/jobs/gperftools, config/jobs/oeedger8r-cpp, config/jobs/openenclave, config/jobs/openenclave-build, config/jobs/openenclave-ci, config/jobs/openenclave-curl, config/jobs/openenclave-mbedtls, config/jobs/openenclave-site, config/jobs/openenclave-template, config/jobs/templates, config/jobs/test-infra, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XL

#435 Lower max concurrency of prow jobs to 1 while sorting out load bugs
  config/jobs/gperftools/gperftools-pre-submits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-pre-submits.yaml
  config/jobs/openenclave-build/openenclave-build-pre-submits.yaml
  config/jobs/openenclave-ci/openenclave-ci-pre-submits.yaml
  config/jobs/openenclave-curl/openenclave-curl-pre-submits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-pre-submits.yaml
  config/jobs/openenclave-site/openenclave-site-pre-submits.yaml
  config/jobs/openenclave-template/openenclave-template-pre-submits.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/public-talks/public-talks-pre-submits.yaml
  config/jobs/templates/jenkins/pre-submits.yml
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra-images/test-infra-images-pre-submits.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, area/config, config/jobs/gperftools, config/jobs/oeedger8r-cpp, config/jobs/openenclave, config/jobs/openenclave-build, config/jobs/openenclave-ci, config/jobs/openenclave-curl, config/jobs/openenclave-mbedtls, config/jobs/openenclave-site, config/jobs/openenclave-template, config/jobs/templates, config/jobs/test-infra, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#411 Various performance and visual improvements
  hack/jenkins_bootstrap.py
  images/jenkinsoperator/Dockerfile
  scripts/jenkins_bootstrap.py
Labels: approved, area/hack, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#442 add refspec for AARCHLinux Test Infra
  config/jenkins/configuration/jobs/openenclave/AArch64GNU1604Debug.yml
  config/jenkins/configuration/jobs/openenclave/AArch64GNU1604Release.yml
  config/jenkins/configuration/jobs/openenclave/AArch64GNU1804Debug.yml
  config/jenkins/configuration/jobs/openenclave/AArch64GNU1804Release.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/AArch64GNU1604Debug.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/AArch64GNU1604Release.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/AArch64GNU1804Debug.yml
  config/jenkins/configuration/jobs/test-infra/openenclave/AArch64GNU1804Release.yml
  config/jobs/templates/config.yml
  config/jobs/templates/jenkins/jobs/test-infra/ArchLinux.yml
Labels: approved, area/config, config/jenkins, config/jobs/templates, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#443 increase jenkins agent hd size to 256
  config/jenkins/configuration/clouds.yml
Labels: approved, area/config, config/jenkins, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#445 Pin versions to last known working versions
  config/jenkins/configuration/clouds.yml
  config/jenkins/kubernetes/jenkins-master-deployment.yml
Labels: approved, area/config, config/jenkins, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#440 remove parameter declaration in oeedgr8r jenkinsFiles
  config/jobs/oeedger8r-cpp/jenkins/RhelBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/oeedger8r-cpp/jenkins/WindowsBuild.Jenkinsfile
Labels: approved, area/config, config/jobs/oeedger8r-cpp, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#441 remove mbedtls params declaration
  config/jobs/openenclave-mbedtls/jenkins/RhelBuild.Jenkinsfile
  config/jobs/openenclave-mbedtls/jenkins/UbuntuBuild.Jenkinsfile
  config/jobs/openenclave-mbedtls/jenkins/WindowsBuild.Jenkinsfile
Labels: approved, area/config, config/jobs/openenclave-mbedtls, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#444 Various improvements on handling side cases
  scripts/jenkins_bootstrap.py
Labels: approved, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/M

#447 Upgrade to openenclave/jenkinsoperator:0.3
  config/jobs/gperftools/gperftools-periodics.yaml
  config/jobs/gperftools/gperftools-pre-submits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-periodics.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-pre-submits.yaml
  config/jobs/openenclave-build/openenclave-build-periodics.yaml
  config/jobs/openenclave-build/openenclave-build-pre-submits.yaml
  config/jobs/openenclave-ci/openenclave-ci-periodics.yaml
  config/jobs/openenclave-ci/openenclave-ci-pre-submits.yaml
  config/jobs/openenclave-curl/openenclave-curl-periodics.yaml
  config/jobs/openenclave-curl/openenclave-curl-pre-submits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-periodics.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-pre-submits.yaml
  config/jobs/openenclave-site/openenclave-site-periodics.yaml
  config/jobs/openenclave-site/openenclave-site-pre-submits.yaml
  config/jobs/openenclave-template/openenclave-template-periodics.yaml
  config/jobs/openenclave-template/openenclave-template-pre-submits.yaml
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/public-talks/public-talks-periodics.yaml
  config/jobs/public-talks/public-talks-pre-submits.yaml
  config/jobs/templates/jenkins/periodics.yml
  config/jobs/templates/jenkins/postsubmits.yml
  config/jobs/templates/jenkins/pre-submits.yml
  config/jobs/templates/test-infra/periodics.yml
  config/jobs/templates/test-infra/postsubmits.yml
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra-images/test-infra-images-periodics.yaml
  config/jobs/test-infra-images/test-infra-images-pre-submits.yaml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, area/config, config/jobs/gperftools, config/jobs/oeedger8r-cpp, config/jobs/openenclave, config/jobs/openenclave-build, config/jobs/openenclave-ci, config/jobs/openenclave-curl, config/jobs/openenclave-mbedtls, config/jobs/openenclave-site, config/jobs/openenclave-template, config/jobs/templates, config/jobs/test-infra, dco-signoff: yes, sig/ci, sig/testing, size/XL

#448 add intel token to config permanently
  config/jobs/openenclave/openenclave-intel-periodics.yaml
  config/prow/config.yaml
Labels: approved, area/config, area/config/prow, dco-signoff: yes, lgtm, sig/ci, sig/testing

#450 encrypt all config info
  config/prow/config.yaml
Labels: approved, area/config, area/config/prow, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/S

#452 Upgrade jenkinsoperator to 0.4
  config/jobs/gperftools/gperftools-periodics.yaml
  config/jobs/gperftools/gperftools-pre-submits.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-periodics.yaml
  config/jobs/oeedger8r-cpp/oeedger8r-cpp-pre-submits.yaml
  config/jobs/openenclave-build/openenclave-build-periodics.yaml
  config/jobs/openenclave-build/openenclave-build-pre-submits.yaml
  config/jobs/openenclave-ci/openenclave-ci-periodics.yaml
  config/jobs/openenclave-ci/openenclave-ci-pre-submits.yaml
  config/jobs/openenclave-curl/openenclave-curl-periodics.yaml
  config/jobs/openenclave-curl/openenclave-curl-pre-submits.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-periodics.yaml
  config/jobs/openenclave-mbedtls/openenclave-mbedtls-pre-submits.yaml
  config/jobs/openenclave-site/openenclave-site-periodics.yaml
  config/jobs/openenclave-site/openenclave-site-pre-submits.yaml
  config/jobs/openenclave-template/openenclave-template-periodics.yaml
  config/jobs/openenclave-template/openenclave-template-pre-submits.yaml
  config/jobs/openenclave/openenclave-periodics.yaml
  config/jobs/openenclave/openenclave-pre-submits.yaml
  config/jobs/public-talks/public-talks-periodics.yaml
  config/jobs/public-talks/public-talks-pre-submits.yaml
  config/jobs/templates/jenkins/periodics.yml
  config/jobs/templates/jenkins/postsubmits.yml
  config/jobs/templates/jenkins/pre-submits.yml
  config/jobs/templates/test-infra/periodics.yml
  config/jobs/templates/test-infra/postsubmits.yml
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra-images/test-infra-images-periodics.yaml
  config/jobs/test-infra-images/test-infra-images-pre-submits.yaml
  config/jobs/test-infra/test-infra-periodics.yaml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, area/config, config/jobs/gperftools, config/jobs/oeedger8r-cpp, config/jobs/openenclave, config/jobs/openenclave-build, config/jobs/openenclave-ci, config/jobs/openenclave-curl, config/jobs/openenclave-mbedtls, config/jobs/openenclave-site, config/jobs/openenclave-template, config/jobs/templates, config/jobs/test-infra, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/XL

#454 fix bug where mass tests are kicked off when prow configs are changed
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, area/config, config/jobs/templates, config/jobs/test-infra, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#449 re/move hack scripts
  hack/OWNERS
  hack/jenkins_bootstrap.py
  scripts/label_sync.sh
Labels: approved, area/hack, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L

#455 Revert "fix bug where mass tests are kicked off when prow configs are…
  config/jobs/templates/test-infra/pre-submits.yml
  config/jobs/test-infra/test-infra-pre-submits.yaml
Labels: approved, area/config, config/jobs/templates, config/jobs/test-infra, dco-signoff: yes, lgtm, sig/ci, sig/testing, size/L
